### ISSUE TITLE
two conditions in a row register as a query (on the condition) and then the other condition

### ISSUE THREAD

**Issue by feste** [probmods/chapters#52]
Also this comes out completely crazy in the version of webchurch that chapters is using. The craziness is fixed in the most up-to-date webchurch.

Here's the code examples that's wrong (In "Patterns of Inference")

```scheme
(define observed-luminance 3.0)

(define samples
   (mh-query
    1000 10

    (define reflectance (gaussian 1 1))
    (define illumination (gaussian 3 0.5))
    (define luminance (* reflectance illumination))

    reflectance

    (condition (= luminance (gaussian observed-luminance 0.1)))
    (condition (= illumination (gaussian 0.5  0.1)))))

(multiviz "Mean reflectance: " (mean samples)
          (hist samples "Reflectance"))
```

If you replace the two conditions with an and statement it takes a reallllly long time to run, but I think it would do the correct thing.

**Comment by longouyang** [comment]
This got fixed at some point.
