### ISSUE TITLE
lambda symbol too small on Android phone

### ISSUE THREAD

**Issue by colcord** [probmods/chapters#60]
Hi, I have a Nexus 5 and Nexus 7. The Lambda symbol in the introduction chapter appears to be completely missing on the Nexus 5. I can zoom into it on the Nexus 7. It's still too small to read. I can see it fine on Chrome on my desktop. Both devices were using Chrome Beta. Happy to test for you. Thanks so much for making this book open source.

(I was hoping the symbol was going to be the pi calculus, but then I can't say I got very far through the first chapter of Milner's Space and Motion of Communicating Agents. I'm only on the introduction of your book.)

**Comment by longouyang** [comment]
It looks like MathJax isn't playing nice with our stylesheet. I couldn't get things to work with 5 minutes of fiddling; I'll roll up my sleeves and take a deeper look later this week.

Btw, the interactive exercises are pretty crucial to grokking the book and the Javascript machinery is pretty compute intensive so I don't recommend using a phone/tablet.

**Comment by longouyang** [comment]
Alright - I've pushed a fix for this. It looks better now on my Nexus 4. Would you mind checking on your Nexus 5 and 7?

**Comment by colcord** [comment]
Yes. Looks much better, once I refresh the pages. Thanks f
