### ISSUE TITLE
Save histograms / scatter plots from the playspace

### ISSUE THREAD

**Issue by fsaad** [probmods/chapters#63]
Hello! Would be helpful to include a 'Download' button for the histogram / scatter plots produced in the play space, for example:

![image](https://cloud.githubusercontent.com/assets/5721897/10711945/2c80e7f6-7a59-11e5-8c0d-ddc89a9dc1cf.png)

It seems the images are inlined, and so `right click > save image as` is not possible.

**Comment by longouyang** [comment]
FYI, I was hoping to get to this sooner but I probably won't be able to start until later next week.

**Comment by longouyang** [comment]
Fixed in fde712aed2feb02f5c8bc6e11fd47f810d9fcdbe

You should be able to right click the charts and download the .svg files now. You might have to clear your cache to get this behavior.
