### ISSUE TITLE
(discrete '(0.2 0.3 0.1 0.4)) 

### ISSUE THREAD

**Issue by toncho11** [probmods/chapters#64]
The following command does not work:

(discrete '(0.2 0.3 0.1 0.4)) 

in 12. Non-parametric models. For me "discrete" is a type of specifier (discrete or continous) rather than a distribution itself.

**Comment by longouyang** [comment]
Ah -- it should be `sample-discrete`. I'll fix this in the next couple days.

**Comment by longouyang** [comment]
Fixed in 35b71e48e49b5e0be5b973c6f6c0638f0028a6d8
